---
Item0:
  id: 272
  damage: 0
  count: 1
Item1:
  id: 275
  damage: 0
  count: 1
Item2:
  id: 274
  damage: 0
  count: 1
Item3:
  id: 273
  damage: 0
  count: 1
Item4:
  id: 320
  damage: 0
  count: 32
Item5:
  id: 264
  damage: 0
  count: 8